In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
#Basic checks 
df_train=pd.read_csv("train.csv")
print("Train data shape--",df_train.shape)
print("Train data columns--",df_train.columns)
df_train.head()

Train data shape-- (318438, 18)
Train data columns-- Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit', 'Stay'],
      dtype='object')


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   
2        3             10                  e                   1   
3        4             26                  b                   2   
4        5             26                  b                   2   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   
2                    X                                  2    anesthesia   
3                    Y                                  2  radiotherapy   
4                    Y                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   
2         S                  E        2.0      31397                7.0   
3         R                  D        2.0      31397                7.0   
4         S                  D        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   
2            Trauma             Extreme                      2  51-60   
3            Trauma             Extreme                      2  51-60   
4            Trauma             Extreme                      2  51-60   

   Admission_Deposit   Stay  
0             4911.0   0-10  
1             5954.0  41-50  
2             4745.0  31-40  
3             7272.0  41-50  
4             5558.0  41-50

In [3]:
df_train.describe()

case_id  Hospital_code  City_Code_Hospital  \
count  318438.000000  318438.000000       318438.000000   
mean   159219.500000      18.318841            4.771717   
std     91925.276847       8.633755            3.102535   
min         1.000000       1.000000            1.000000   
25%     79610.250000      11.000000            2.000000   
50%    159219.500000      19.000000            5.000000   
75%    238828.750000      26.000000            7.000000   
max    318438.000000      32.000000           13.000000   

       Available Extra Rooms in Hospital      Bed Grade      patientid  \
count                      318438.000000  318325.000000  318438.000000   
mean                            3.197627       2.625807   65747.579472   
std                             1.168171       0.873146   37979.936440   
min                             0.000000       1.000000       1.000000   
25%                             2.000000       2.000000   32847.000000   
50%                             3.000000       3.000000   65724.500000   
75%                             4.000000       3.000000   98470.000000   
max                            24.000000       4.000000  131624.000000   

       City_Code_Patient  Visitors with Patient  Admission_Deposit  
count      313906.000000          318438.000000      318438.000000  
mean            7.251859               3.284099        4880.749392  
std             4.745266               1.764061        1086.776254  
min             1.000000               0.000000        1800.000000  
25%             4.000000               2.000000        4186.000000  
50%             8.000000               3.000000        4741.000000  
75%             8.000000               4.000000        5409.000000  
max            38.000000              32.000000       11008.000000

In [4]:
df_train.columns

Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit', 'Stay'],
      dtype='object')

In [5]:
print('Hospital_type_code',df_train['Hospital_type_code'].unique(),"\n",
      'Hospital_code',df_train['Hospital_code'].unique(),"\n",      
    'Available Extra Rooms in Hospital',df_train['Available Extra Rooms in Hospital'].unique(),"\n",
     "Department",df_train.Department.unique(),"\n",
"Ward_Type",df_train.Ward_Type.unique(),"\n",
'Bed Grade',df_train['Bed Grade'].unique(),"\n"
      "patientid",df_train.patientid.unique(),"\n"
      "City_Code_Patient",df_train.City_Code_Patient.unique(),"\n"
      'Type of Admission',df_train['Type of Admission'].unique(),"\n"
      'Severity of Illness',df_train['Severity of Illness'].unique(),"\n"
      'Visitors with Patient',df_train['Visitors with Patient'].unique(),"\n"
      "Age",df_train.Age.unique(),"\n"
      "Admission_Deposit",df_train.Admission_Deposit.unique(),"\n"
      "Stay",df_train.Stay.unique(),"\n"
)

Hospital_type_code ['c' 'e' 'b' 'a' 'f' 'd' 'g'] 
 Hospital_code [ 8  2 10 26 23 32  1 22 16  9  6 29 12  3 21 28 27 19  5 14 13 31 24 17
 25 15 11 30 18  4  7 20] 
 Available Extra Rooms in Hospital [ 3  2  1  4  6  5  7  8  9 10 12  0 11 20 14 21 13 24] 
 Department ['radiotherapy' 'anesthesia' 'gynecology' 'TB & Chest disease' 'surgery'] 
 Ward_Type ['R' 'S' 'Q' 'P' 'T' 'U'] 
 Bed Grade [ 2.  3.  4.  1. nan] 
patientid [ 31397  63418   8088 ... 125235  91081  21641] 
City_Code_Patient [ 7.  8.  2.  5.  6.  3.  4.  1.  9. 14. nan 25. 15. 12. 10. 28. 24. 23.
 20. 11. 13. 21. 18. 16. 26. 27. 22. 19. 31. 34. 32. 30. 29. 37. 33. 35.
 36. 38.] 
Type of Admission ['Emergency' 'Trauma' 'Urgent'] 
Severity of Illness ['Extreme' 'Moderate' 'Minor'] 
Visitors with Patient [ 2  4  3  8  6  7 13  5  1 10 15 11 12  9 24 16 14 20  0 19 18 17 23 21
 32 30 22 25] 
Age ['51-60' '71-80' '31-40' '41-50' '81-90' '61-70' '21-30' '11-20' '0-10'
 '91-100'] 
Admission_Deposit [4911. 5954. 4745. ... 1937. 94

In [6]:
#Replacing missing values with fill with above value
df_null=df_train
df_null["Bed Grade"].fillna( method ='ffill', inplace = True) 
df_null["City_Code_Patient"].fillna( method ='ffill', inplace = True) 

In [7]:
# creating dummy's
df_dummy = pd.get_dummies(df_null, 
                          columns = [ 'Hospital_code',
                                     'Hospital_type_code',
                                     'City_Code_Hospital',
                                     'Hospital_region_code',
                                     'Department',
                                     'Ward_Type', 
                                     'Ward_Facility_Code',
                                     'Bed Grade',
                                     'Severity of Illness',
                                     'Age', 
                                     'Type of Admission',
                                     'City_Code_Patient'
       ],drop_first=True)


In [8]:
df_dummy.columns

Index(['case_id', 'Available Extra Rooms in Hospital', 'patientid',
       'Visitors with Patient', 'Admission_Deposit', 'Stay', 'Hospital_code_2',
       'Hospital_code_3', 'Hospital_code_4', 'Hospital_code_5',
       ...
       'City_Code_Patient_29.0', 'City_Code_Patient_30.0',
       'City_Code_Patient_31.0', 'City_Code_Patient_32.0',
       'City_Code_Patient_33.0', 'City_Code_Patient_34.0',
       'City_Code_Patient_35.0', 'City_Code_Patient_36.0',
       'City_Code_Patient_37.0', 'City_Code_Patient_38.0'],
      dtype='object', length=121)

In [9]:
import pickle
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.naive_bayes import BernoulliNB,GaussianNB,ComplementNB 
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,f1_score
#IMPORTING LIBRARY'S
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

# Feature_Extraction

In [42]:
X = df_dummy.loc[:, df_dummy.columns != 'Stay']
y = df_dummy.loc[:, df_dummy.columns == 'Stay']
X.drop(['case_id','patientid'],axis=1,inplace=True)

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
from sklearn import datasets
from sklearn.feature_selection import RFE
logreg = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
rfe = RFE(logreg, 70)
rfe = rfe.fit(X_train, y_train.values.ravel())
print(rfe.support_)
print(rfe.ranking_)

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages

In [23]:
# #extracted features 20 features acc 38
# cols=[ 'Visitors with Patient',
#  'Hospital_code_3',
#  'Hospital_code_7',
#  'Hospital_code_24',
#  'Hospital_code_31',
#  'City_Code_Hospital_7',
#  'City_Code_Hospital_9',
#  'Hospital_region_code_Y',
#  'Hospital_region_code_Z',
#  'Ward_Type_Q',
#  'Ward_Type_R',
#  'Ward_Type_S',
#  'Ward_Facility_Code_C',
#  'Ward_Facility_Code_E',
#  'Ward_Facility_Code_F',
#  'Severity of Illness_Minor',
#  'Age_11-20',
#  'Age_81-90',
#  'City_Code_Patient_2.0',
#  'City_Code_Patient_10.0'
# ]

In [33]:
# 50 Features accu 40%
cols=['Available Extra Rooms in Hospital',
 'Visitors with Patient',
 'Hospital_code_3',
 'Hospital_code_4',
 'Hospital_code_7',
 'Hospital_code_12',
 'Hospital_code_13',
 'Hospital_code_14',
 'Hospital_code_16',
 'Hospital_code_17',
 'Hospital_code_18',
 'Hospital_code_19',
 'Hospital_code_21',
 'Hospital_code_24',
 'Hospital_code_25',
 'Hospital_code_26',
 'Hospital_code_30',
 'Hospital_code_31',
 'Hospital_type_code_f',
 'Hospital_type_code_g',
 'City_Code_Hospital_3',
 'City_Code_Hospital_7',
 'City_Code_Hospital_9',
 'Hospital_region_code_Y',
 'Hospital_region_code_Z',
 'Department_anesthesia',
 'Ward_Type_Q',
 'Ward_Type_R',
 'Ward_Type_S',
 'Ward_Facility_Code_C',
 'Ward_Facility_Code_E',
 'Ward_Facility_Code_F',
 'Bed Grade_2.0',
 'Bed Grade_3.0',
 'Bed Grade_4.0',
 'Severity of Illness_Minor',
 'Severity of Illness_Moderate',
 'Age_11-20',
 'Age_41-50',
 'Age_51-60',
 'Age_61-70',
 'Age_81-90',
 'Type of Admission_Trauma',
 'Type of Admission_Urgent',
 'City_Code_Patient_2.0',
 'City_Code_Patient_3.0',
 'City_Code_Patient_8.0',
 'City_Code_Patient_10.0',
 'City_Code_Patient_12.0',
 'City_Code_Patient_21.0']

In [34]:
X = df_dummy[cols]
y = df_dummy.loc[:, df_dummy.columns == 'Stay']

# Model Fit

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)
logreg = LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)
logreg.fit(X_train, y_train)

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [36]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.40


In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[   66  3970  3471   236     0    26     0     0     0     0     1]
 [   36 12606 10921  1618     0   865     0     0     0     0     3]
 [   38  8279 18692  1160     0   464     0     0     0     0    43]
 [   11  3696  7189  3958     0  3137     0     1     0     0    66]
 [    5   838  2311   382     0   270     0     0     0     0    35]
 [    5  1042  1822  3033     0  5472     0     0     1     0   172]
 [    0   141   476   136     0   176     0     0     0     0    27]
 [    0   242   371   995     0  1620     0     0     0     0   246]
 [    1    65    85   152     0  1089     0     1     0     0   171]
 [    0    53   108   243     0   385     0     0     0     0   132]
 [    1    92   141   191     0   985     0     1     0     0   818]]


In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


                    precision    recall  f1-score   support

              0-10       0.40      0.01      0.02      7770
             11-20       0.41      0.48      0.44     26049
             21-30       0.41      0.65      0.50     28676
             31-40       0.33      0.22      0.26     18058
             41-50       0.00      0.00      0.00      3841
             51-60       0.38      0.47      0.42     11547
             61-70       0.00      0.00      0.00       956
             71-80       0.00      0.00      0.00      3474
             81-90       0.00      0.00      0.00      1564
            91-100       0.00      0.00      0.00       921
More than 100 Days       0.48      0.37      0.41      2229

         micro avg       0.40      0.40      0.40    105085
         macro avg       0.22      0.20      0.19    105085
      weighted avg       0.35      0.40      0.35    105085



C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Predictions

In [39]:
df_test=pd.read_csv('test.csv')
df_dummy_test = pd.get_dummies(df_test, columns = [ 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital','Hospital_region_code','Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
                'Severity of Illness','Age', 'Type of Admission','City_Code_Patient'
       ],drop_first=True)


In [40]:
df_dummy_test=df_dummy_test[cols]

In [41]:
pred=logreg.predict(df_dummy_test)
df_pred=pd.DataFrame(pred,columns=['Stay'])
df_test_prd_emp=df_test[['case_id']]
submission=df_test_prd_emp.join(df_pred)
submission.to_csv("Sub_log_fil_50features_v2.csv",index=False)